### ISSUE TITLE
My releases always have -SNAPSHOT in them

### ISSUE THREAD

**Issue by stewartbryson** [shipkit/shipkit-changelog#110]
`build.gradle` snippet:
```
githubRelease {
   dependsOn generateChangelog
   repository = githubRepo
   changelog = tasks.generateChangelog.outputFile
   newTagRevision = System.getenv("GITHUB_SHA")
}
```

`version.properties`:
```
version=0.0.*
```

GitHub Actions workflow snippet:
```
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

...

  - name: github-release
    if: ${{ github.event_name == 'push' }}
    uses: gradle/gradle-build-action@v2
    with:
      arguments: githubRelease
```

I'm not sure I understand how to produce a release without a snapshot. I am running `githubRelease` on any push to `main`... so this is effectively any PRs that are merged. But since there are 1 or more commits since the last tag (as there always will be), I always get a published release with a `-SNAPSHOT` in the name.

For instance... if my most recent tag is `v0.0.1`, and I have a commit merging in through a PR, then `githubRelease` will publish `v0.0.2-SNAPSHOT`. But on an accepted PR merging into `main`, I want `githubRelease` to publish `v0.0.2`. Is there a step I am omitting before running `githubRelease`?
