### ISSUE TITLE
Possibility to customize changelog format

### ISSUE THREAD

**Issue by mstachniuk** [shipkit/shipkit-changelog#23]
Current changelog format is good for Open Source project. However for non-OSS is not important who and how much commit. 
And other customizations should be possible like header, footer, date format. See: https://github.com/mockito/shipkit/issues/370

The implementation may create a JSON file as mid step then everyone can generate whatever is needed.

**Comment by mockitoguy** [comment]
I'd like to see customers asking for it first ;-) I'd like to avoid complexity and evolving the plugin into something that is hard to maintain. My experience with offering "configuration" for formatting that it is a never-ending story of expanding the configuration to support more formatting use cases.

> The implementation may create a JSON file as mid step then everyone can generate whatever is needed.

This would be my preference.

Thanks for reporting!

**Comment by beatngu13** [comment]
We at JUnit Pioneer would also appreciate customization to a certain degree:

https://github.com/junit-pioneer/junit-pioneer/issues/622

Similar to [GitHub's release notes generator](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes), it would helpful to filter tags and create categories. Here is an example configuration:

```yaml
# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
```

Do you have any plans for such customization options?
